{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-grpc",
    "version": "0.0.13-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.13-TRIAL.jar",
          "url": "specmatic-grpc-0.0.13-TRIAL.jar",
          "size": 189947,
          "sha512": "e4ef63cf660972aa26c9a3341c842eeaf96fb48b29c7aeb4029d736905a41ac5f9d8114dda5be6b3274d1b8773c68e9355456cec8a05e2bb547ace801808f2c9",
          "sha256": "ac41d4c82b767771dc24ecdb283d516d8b3793da3bd770a19fc9d3eb7ab81a63",
          "sha1": "8bb37068d7430b8dc53b3948eb1460533b44424f",
          "md5": "6e6b59c7beb69c1beddd7bdecd7ca4e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.specmatic",
          "module": "specmatic-executable",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "io.specmatic",
          "module": "junit5-support",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.2"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.12.5"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-schema",
          "version": {
            "requires": "4.9.9"
          }
        },
        {
          "group": "com.github.os72",
          "module": "protoc-jar",
          "version": {
            "requires": "3.11.4"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-bom",
          "version": {
            "requires": "1.63.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty-shaded"
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf"
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub"
        },
        {
          "group": "io.grpc",
          "module": "grpc-services"
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "build.buf",
          "module": "protovalidate",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-grpc-0.0.13-TRIAL.jar",
          "url": "specmatic-grpc-0.0.13-TRIAL.jar",
          "size": 189947,
          "sha512": "e4ef63cf660972aa26c9a3341c842eeaf96fb48b29c7aeb4029d736905a41ac5f9d8114dda5be6b3274d1b8773c68e9355456cec8a05e2bb547ace801808f2c9",
          "sha256": "ac41d4c82b767771dc24ecdb283d516d8b3793da3bd770a19fc9d3eb7ab81a63",
          "sha1": "8bb37068d7430b8dc53b3948eb1460533b44424f",
          "md5": "6e6b59c7beb69c1beddd7bdecd7ca4e7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "specmatic-grpc-0.0.13-TRIAL-all.jar",
          "url": "specmatic-grpc-0.0.13-TRIAL-all.jar",
          "size": 99708732,
          "sha512": "0ba89b51e3c91d8064b6f4d31e8b60f7efdd9ea6cec76b99c5d1d1239496d8a12a30187bd508b7431bde0abc576e902093209d3776ed65716bac1326fdce5815",
          "sha256": "c95720ea650a1709373c109abeded8c10a83f069adb08203d57f48b50e203da1",
          "sha1": "6d8a8b0a0e7cf58b0d8a7d8926fd175cd9351f36",
          "md5": "c9044fc6fbe6214a9c408354d4fa0521"
        }
      ]
    }
  ]
}
