name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Print the config file
      run: cat $(pwd)/specmatic.yaml
    
    - name: Run the stub
      run: |
        docker run -p 9090:9090 \
        -v "$(pwd)/specmatic.yaml:/usr/src/app/specmatic.yaml" \
        specmatic/specmatic-grpc virtualize --protoc-version="3.23.4" --port=9090   
